server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: loan-schedule-api

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springdoc: INFO
    org.hibernate: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true